In [ ]:
import pandas

x = [1, 2, 3, 4]
y = [5, 6, 7, 8]


In [ ]:
!ls -la

# 1st level
text...
## 2nd level
text...
### 3rd level
text...

Latex_formule : $$ \mathbf {asd + sdf} \cdot efg $$

In [ ]:
!echo 5

In [ ]:
%%bash
var=5
for ((i = 0; i < var; i++))
do
    echo $var
done

In [ ]:
%lsmagic

In [ ]:
%pylab inline
y = range(11)
# plot(y)
z = [x ** 3 for x in range(10)]
plot(z)

In [ ]:
%pycat ex.py  # like linux terminal cmd 'cat file', but works invisibly


## Массивы обычные и NumPy

In [1]:
# ususal arrays can't be multiplied
# numpy arras can be
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = x * y  # it's OK
z          # works normal, counts not scalar product, but vector of products, elem by elem

array([ 4, 10, 18])

In [ ]:
np.linalg?

In [ ]:
t = np.dot(x, y)
t == 1 * 4 + 2 * 5 + 3 * 6

In [ ]:
import matplotlib.pyplot as plt
# plt?

import numpy as np
x = np.arange(0, 6, 0.1)
y = np.sin(x)
plt.plot(x, y)

# Experiments

In [19]:
import numpy as np
A = np.array(
    [[1, 2],
     [4, 7]]
)
b = np.array([3, 4])
x = np.linalg.solve(A, b)
print('A = \n', A)
print('x = ', x)
print('A^{-1}b = ', np.linalg.inv(A).dot(b))
print('A = \n', A)
print('Ax = ', A.dot(x))
print('b = ', b)

A = 
 [[1 2]
 [4 7]]
x =  [-13.   8.]
A^{-1}b =  [-13.   8.]
A = 
 [[1 2]
 [4 7]]
Ax =  [3. 4.]
b =  [3 4]


In [13]:
?np.linalg.inv

In [7]:
?np

In [13]:
np.lookfor('in a row')

Search results for 'in a row'
-----------------------------
numpy.row_stack
    Stack arrays in sequence vertically (row wise).
numpy.loadtxt
    Load data from a text file.
numpy.ma.mask_rows
    Mask rows of a 2D array that contain masked values.
numpy.fliplr
    Flip array in the left/right direction.
numpy.ma.row_stack
    Stack arrays in sequence vertically (row wise).
numpy.vsplit
    Split an array into multiple sub-arrays vertically (row-wise).
numpy.ma.mask_rowcols
    Mask rows and/or columns of a 2D array that contain masked values.
numpy.ma.compress_rows
    Suppress whole rows of a 2-D array that contain masked values.
numpy.ma.mask_cols
    Mask columns of a 2D array that contain masked values.
numpy.ma.compress_rowcols
    Suppress the rows and/or columns of a 2-D array that contain
numpy.matrix.flatten
    Return a flattened copy of the matrix.
numpy.testing.assert_warns
    Fail unless the given callable throws the specified warning.
numpy.ma.compress_cols
    Suppress